security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        administrators:
            entity: { class: AppBundle:User }
        api_key_user_provider:
            id: app.security.api_key_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|fonts|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: app.security.apikey_authenticator
        main:
            pattern: ^/
            form_login:
                csrf_provider: form.csrf_provider
                login_path: security_login
                check_path: security_login_check
            logout:       true
            anonymous:    true
            remember_me:
                key:      "%secret%"

    access_control:
        - { path: ^(/[a-z]+)?/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^(/[a-z]+)?/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^(/[a-z]+)?/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^(/[a-z]+)?/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }