parameters:
    uecode.api_key.provider.api_key.class:       Uecode\Bundle\ApiKeyBundle\Security\Authentication\Provider\ApiKeyProvider
    uecode.api_key.listener.api_key.class:       Uecode\Bundle\ApiKeyBundle\Security\Firewall\ApiKeyListener

    uecode.api_key.extractor.query.class:        Uecode\Bundle\ApiKeyBundle\Extractor\QueryExtractor
    uecode.api_key.extractor.header.class:       Uecode\Bundle\ApiKeyBundle\Extractor\HeaderExtractor

services:
    uecode.api_key.provider.api_key:
        class: %uecode.api_key.provider.api_key.class%
        arguments: [""]
    uecode.api_key.listener.api_key:
        class: %uecode.api_key.listener.api_key.class%
        arguments: [@security.context, @security.authentication.manager, @uecode.api_key.extractor]

    uecode.api_key.extractor.query:
        class: %uecode.api_key.extractor.query.class%
        arguments: [%uecode.api_key.parameter_name%]
        public: false
    uecode.api_key.extractor.header:
        class: %uecode.api_key.extractor.header.class%
        arguments: [%uecode.api_key.parameter_name%]
        public: false
